### ISSUE TITLE
Unable to edit source information

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/DAP-System#333]
When trying to edit a source name, a error is thrown (see screencap below).  Also note that CPS is showing a different value for organization when editing a row than when not editing.  

![image](https://cloud.githubusercontent.com/assets/1654485/5901445/ea7451e2-a572-11e4-927b-1f89dd915fe9.png)

**Comment by seustachi** [comment]
I could not reproduce the error. However, I found something poorly implemented that explains the second issue (the different value in editing or not editing). 

The organization is displayed using a filter ( $filter('filter') etc ....) and the rule for the matching is not exact equality. For instance, if the id of the organization to match is 5, it might as well display the org with the id 15, or 50, or any containing '5'.

I suspect the issue is present is all the administration pages.

**Comment by cjhendrix** [comment]
Weird.  I tried it a couple of times yesterday in chrome and no luck.  I thought I should try it in another browser but was too rushed.  Today, I was able to edit the source name with no problem.   I'll close this one and open one for the name display issue you describe above.

**Comment by seustachi** [comment]
Ok, we can reopen if this happens again.
